#!/bin/bash
#
# From Destroy All Software screencast #10, at:
# http://destroyallsoftware.com/screencasts/catalog/fast-tests-with-and-without-rails
#
# Put this in the script/ directory of your Rails app, then run it with a spec
# filename. If the spec uses spec_helper, it'll be run inside Bundler.
# Otherwise, it'll be run directly with whatever `spec` executable is on the
# path.

set -e

if [ $# -gt 0 ]; then # we have args
    filename=$1
else # we have no args
    filename='spec'
fi

command='jasmine-node --captureExceptions '

$command $filename
